from setuptools import setup, find_packages

setup(
    name="heart-protectors",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.26.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "joblib>=1.3.0",
        "pytest>=7.4.0",
        "jupyter>=1.0.0",
        "notebook>=7.0.0",
        "kaggle>=1.5.16",
        "ipykernel>=6.25.0",
        "setuptools>=68.0.0",
    ],
    author="Heart Protectors Team",
    author_email="your.email@example.com",
    description="A machine learning project for predicting heart failure risks",
    keywords="heart failure, machine learning, prediction",
    url="https://github.com/yourusername/heart-protectors",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Healthcare Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    python_requires=">=3.8",
)